### ISSUE TITLE
Code for reproduction

### ISSUE THREAD

**Issue by Mirorrn** [MurpheyLab/DistNav#7]
Hello!
I like your work very much! Any chance you will publish the rest of the code as well? Or at least the exact environment so that one can reproduce the results?

**Comment by MuchenSun** [comment]
Hi! 

Thank you for your interest! We anticipate looking into the relevant code, and will update you by the end of the month.

Thank you!
Muchen

**Comment by MuchenSun** [comment]
Hi!

We are preparing to release the code. Thank you for your patience!

Muchen

**Comment by MuchenSun** [comment]
Hi!

The code for running the ETH experiment in our paper is available at: [https://github.com/MurpheyLab/DistNav-ETH-Evaluation](https://github.com/MurpheyLab/DistNav-ETH-Evaluation).
For the ORCA experiment, we use the toolkit from [https://github.com/vita-epfl/CrowdNav](https://github.com/vita-epfl/CrowdNav).

Thank you!
Muchen
