### ISSUE TITLE
Kinematic constraints of a robot

### ISSUE THREAD

**Issue by Mirorrn** [MurpheyLab/DistNav#8]
Hello @MuchenSun ,

Is it possible to consider the kinematic constraints of a robot in the planning algorithm presented here?

Thanks a lot :)

**Comment by MuchenSun** [comment]
Hi @Mirorrn,

Explicit kinematic constraint is not supported by the algorithm. One workaround is to use the trajectories generated as reference trajectories for lower level controllers, such as LQR.
